MODEL:
  DEVICE: 'cuda'
  META_ARCHITECTURE: "YOLOS"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  YOLOS:
    NUM_CLASSES: 2
    DET_TOKEN_NUM: 100
    BACKBONE_NAME: 'small_dWr'
    INIT_PE_SIZE: (512, 864)
    MID_PE_SIZE: (512, 864)
  LOSS:
    DICE_LOSS_COEF: 1
    BBOX_LOSS_COEF: 5
    GIOU_LOSS_COEF: 2
    EOS_COEF: 0.1
  MATCHER:
    SET_COST_CLASS: 1
    SET_COST_BBOX: 5
    SET_COST_GIOU: 2
    

SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  LR_BACKBONE: 0.00001
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  CLIP_MAX_NORM: 0.1

  # MAX_ITER: 5000 #
  # WARMUP_ITERS: 0 #
  # BASE_LR_END: 0.0000001 #
  # LR_SCHEDULER_NAME: "WarmupCosineLR" #


INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 4000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 4
VERSION: 2
